apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-toleration
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "1Gi"
            cpu: 1
      tolerations: # <----- TOLERATIONS
      - key: "time"
        operator: "Equal"
        value: "credito"
        effect: "NoSchedule" # NoExecute 